# Generated by Django 2.2.7 on 2019-12-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
        ),
    ]
