# Generated by Django 2.2.7 on 2019-12-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de Publicacion'),
        ),
    ]
