# Generated by Django 2.2.7 on 2019-12-12 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191209_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 21, 1, 23, 219168), verbose_name='Fecha de Publicacion'),
        ),
    ]
