# Generated by Django 2.2.7 on 2019-12-12 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191211_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 21, 1, 45, 224648), verbose_name='Fecha de Publicacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
