# Generated by Django 2.2.7 on 2019-12-23 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191222_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewCounter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 19, 22, 46, 5836), verbose_name='Fecha de Publicacion'),
        ),
    ]
