# Generated by Django 2.2.7 on 2020-01-26 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191224_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 4, 54, 10, 110396), verbose_name='Fecha de Publicacion'),
        ),
    ]
