# Generated by Django 2.2.10 on 2021-03-29 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200324_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 23, 24, 57, 591735), verbose_name='Fecha de Publicacion'),
        ),
    ]
