# Generated by Django 2.2.10 on 2021-04-02 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210328_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrimage',
            name='image',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.formulad.org%2Fes%2Fphotogalleries%2F2017-08-09-gallery-not-found%2F&psig=AOvVaw1sNW9BAEhcHcDtmF-wvnm4&ust=1617411070167000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLis6vir3u8CFQAAAAAdAAAAABAD'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 21, 51, 56, 107108), verbose_name='Fecha de Publicacion'),
        ),
    ]
