# Generated by Django 2.2.10 on 2021-04-02 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210401_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 15, 12, 29, 826561), verbose_name='Fecha de Publicacion'),
        ),
    ]
